name: Build Android

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java-version: ['16', '17']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Build gradle
        run: ./gradlew build
